AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  drew-sandbox

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 100
    MemorySize: 2560
    CodeUri: ./

Resources:
  DrewAllPurposeLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        External:
          - aws-sdk
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - ./drew-all-purpose-lambda.ts
    Properties:
      Architectures:
        - arm64      
      Timeout: 900
      FunctionName: drew-all-purpose-lambda
      Handler: drew-all-purpose-lambda.handler
      VpcConfig:
        SecurityGroupIds: ['sg-02e68dac628a90854']
        SubnetIds: [ 'subnet-057d4e89380eca5f8', 'subnet-0c97044b6245eff83']
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:*"
                - "rds-db:*"
                - "ssm:*"
                - "lambda:*"
                - "cloudwatch:*"
                - "s3:*"
              Resource: "*"
      Environment:
        Variables:
          QUERY_LIMIT: 25
          ORPHANED_EVENTS_URL: 'https://breeding-np.ag/seed-operations-orphaned-events-api/orphaned-events-api'
          VELOCITY: true
          FTS: false
